trigger:
- main

pool: 'ookok'

variables:
  vmImageName: 'ubuntu-latest'
  terraformVersion: '0.15.1'

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: $(terraformVersion)

- task: AzureCLI@2
  inputs:
    azureSubscription: 'connection abc'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      cd terraform
      terraform init
      terraform plan
      terraform apply -auto-approve

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'